### ISSUE TITLE
Can't Install

### ISSUE THREAD

**Issue by kevkevkevin** [AlexEdimensionz/Todoyu-PHP7.x#12]
![image](https://github.com/e-dimensionz/Todoyu-PHP7.x/assets/20296381/98ca7295-dbda-40da-b450-271b01d88282)
Im getting this error :(

**Comment by AlexEdimensionz** [comment]
Hi Kevin
Do you have the mysql and mcrypt modules installed for PHP?
What operating system are you on?

One more thing - Are you trying to install the version from this repo?
It should by looking for 'mysqli' instead of 'mysql'

**Comment by kevkevkevin** [comment]
Windows, i uploaded it on my hosting server and this error appear.

**Comment by AlexEdimensionz** [comment]
Then the issue would be related to missing php modules.
If you are sure the modules are installed, let me know and i can see where we can go from there

**Comment by AlexEdimensionz** [comment]
Closing this ticket. Reopen it if you still have an issue
