### ISSUE TITLE
Loginform not displayed

### ISSUE THREAD

**Issue by gitstefan7** [AlexEdimensionz/Todoyu-PHP7.x#13]
The Loginform is not displayed. New Bug since 26th june 2023.

**Comment by ineswillenbrock** [comment]
I can confirm it.

**Comment by AlexEdimensionz** [comment]
Hi guys. I have uploaded an update that should fix the login page issue.
It's related to the pre-existing news feed. I have disabled the news feed

If you don't want to re-upload everything, you can just copy the following file
**ext/loginpage/model/TodoyuLoginpagePanelWidgetLoginNews.class.php**

Or you can change line 57 on that file to read
`	'content'	=> '' `

**Comment by gitstefan7** [comment]
Thanks for fixing! God Job!
