### ISSUE TITLE
Issue with file uploads

### ISSUE THREAD

**Issue by jrosetto** [AlexEdimensionz/Todoyu-PHP7.x#4]
I have the latest version in production now so it is getting tested pretty heavily.

My receptionist creates a new project and at the bottom you have the option to 'Upload New Asset'.  She goes through the process and selects a file and clicks save on the project creation but the file never uploads and no errors in todoyu error log or apache.

After you create the project and click 'Assets' under the project you can 'Add New File' and it uploads correctly.

I explained to them to only use the Asset tab after the project creation so it isn't an issue for us but thought I would point it out.

**Comment by AlexEdimensionz** [comment]
Thank you. I will check this out

**Comment by jrosetto** [comment]
Was wondering if you every had any luck on fixing this issue?

**Comment by melissa-edimensionz** [comment]
I have no issue uploading PDFs and images.  What file type is is being uploaded?

**Comment by jrosetto** [comment]
Any type of file that I attempt to upload while creating a project never gets attached.  But if i create the project, click on assets, and upload it from there it uploads and shows correctly.

**Comment by melissa-edimensionz** [comment]
Sorry, your right. Just tested on New/Edit Project - asset failed, only working on tasks. Fix coming

**Comment by jrosetto** [comment]
Appreciate it.

**Comment by jrosetto** [comment]
Checking in to see if you have made any progress on this?

**Comment by AlexEdimensionz** [comment]
Sorry for the delay. We are going to be releasing an update to the package with an update manager and a plugin installer/updater feature and data API. This bug fix will be included. Working to release it in our down by the end of the year. We are also reworking the theme for mobile-friendliness and bigger viewports

**Comment by jrosetto** [comment]
Any updates?

**Comment by AlexEdimensionz** [comment]
Can you pull the latest changes and see if this is fixed for you?

**Comment by AlexEdimensionz** [comment]
The issue should be fixed. Open a new ticket if it's not.
