### ISSUE TITLE
PHP 7.4 Troubles

### ISSUE THREAD

**Issue by ineswillenbrock** [AlexEdimensionz/Todoyu-PHP7.x#6]
Do you plan to port it to PHP 7.4 or even 8?
Right now it's running fine on PHP 7.2 which is not supported any more but throws errors on PHP 7.4

Thank you for your time!

regards - Ines

**Comment by AlexEdimensionz** [comment]
Hi. Thank you for reporting this. I will be checking against PHP 7.4

**Comment by AlexEdimensionz** [comment]
Hi Ines,
Can you pull the latest changes and see if you are still getting errors?

If you still have errors, can  you send paste relevant logfile sections in this ticket?

**Comment by ineswillenbrock** [comment]
Will do, but it'll have to wait a few days. 
Sorry for that!

**Comment by ineswillenbrock** [comment]
Grabbed the sources today and at the first glance it's fine -- at least if one just drops the db.conf into the new sources.
I've not found anything PHP 7.4 specific, but might have a few new issues, if those are not just "don't know how do to it right"

Just to clarify it: I use todoyu as project- and timetracker and not much of other functionality

**Comment by AlexEdimensionz** [comment]
If you can list some of the issues, I can see if I can help
