### ISSUE TITLE
Send Email

### ISSUE THREAD

**Issue by oenrico** [AlexEdimensionz/Todoyu-PHP7.x#7]
Hi 
Compliment for project !!!
I have a problem for the send email 

I create SMTP account in ToDoyu
The request arrive but not send 

I have a my server email but not send email ?? 

There is solution

**Comment by oenrico** [comment]
i set paramenter in  class.phpmailer.php end funnction

**Comment by AlexEdimensionz** [comment]
And it worked?  Great!

**Comment by oenrico** [comment]
Yes😀
 

 
 


Da: AlexEdimensionz ***@***.***>
A: e-dimensionz/Todoyu-PHP7.x ***@***.***>
Cc: Enrico ***@***.***>State change ***@***.***>
Data: 6 aprile 2021 11.41.23 CEST
Oggetto: Re: [e-dimensionz/Todoyu-PHP7.x] Send Email (#7)




And it worked? Great!

**Comment by oenrico** [comment]
Yesss
