### ISSUE TITLE
Info for notification email event calendar

### ISSUE THREAD

**Issue by oenrico** [AlexEdimensionz/Todoyu-PHP7.x#8]
Hi 
is it possibile info function crontab because in documentation there isn't info

Thank you very mutch

**Comment by AlexEdimensionz** [comment]
Hi oenrico, 
We took this project over from "Snowflake GmbH" and we are in the process of transitioning/updating it. I will help you how I can, however.

What are you looking to do?

**Comment by oenrico** [comment]
Hi
 
I create event in calendar but not arrive notification before x time

**Comment by oenrico** [comment]
another error in plugin calendar

Log in nginx

#0 /home/oe/todo/ext/calendar/model/TodoyuCalendarViewWeek.class.php(122): TodoyuCalendarEventElementWeek->render(1617660000)
#1 /home/oe/todo/ext/calendar/model/TodoyuCalendarViewWeek.class.php(54): TodoyuCalendarViewWeek->renderEventsPerDay()
#2 /home/oe/todo/ext/calendar/model/TodoyuCalendarCalendarRenderer.class.php(108): TodoyuCalendarViewWeek->render()
#3 /home/oe/todo/ext/calendar/model/TodoyuCalendarCalendarRenderer.class.php(60): TodoyuCalendarCalendarRenderer::renderBodyWeek(1617660000, Array)
#4 /home/oe/todo/ext/calendar/controller/TodoyuCalendarCalendarActionController.class.php(55): TodoyuCalendarCalendarRenderer::renderBody('wee" while reading response $
2021/04/06 16:29:01 [error] 1335#1335: *2437 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to TodoyuCalendarEventElemen$
Stack trace:

**Comment by AlexEdimensionz** [comment]
Can you tell me what action you were doing before that error happened?

Creating calendar entry? Updating? Loading calendar page? etc
