### ISSUE TITLE
Possible Issue: Export of Project Time Sheets

### ISSUE THREAD

**Issue by ineswillenbrock** [AlexEdimensionz/Todoyu-PHP7.x#9]
todoyu from april, 9th 2021 with apache 2.4.46 and PHP 7.4.16:

If I try to export a time sheet with or without person/employer/project/customer and dates set I get an error 503 from apache:
`"GET /todoyu-3/index.php?ext=daytracks&controller=export&export%5Bemployee%5D=&export%5Bemployer%5D=&export%5Bproject%5D=&export%5Bcompany%5D=&export%5Bdate_start%5D=04%2F01%2F2021&export%5Bdate_end%5D=04%2F30%2F2021&action=download HTTP/1.1" 503 `

**Comment by AlexEdimensionz** [comment]
Can you paste the output from the PHP error log?

**Comment by ineswillenbrock** [comment]
Sure:
`6cdf1a3872 :: 2021-04-19 23:05:30 - L:3 - U:admin [core/model/TodoyuExportCSV.class.php:29] :: PHP ERROR: [2] Declaration of TodoyuExportCSV::download($filename = '') should be compatible with TodoyuExportBase::download($type, $filename = '')`

**Comment by ineswillenbrock** [comment]
If you change the following in core/model/TodoyuExportCSV.class.php, you'll get the downloads of the Time Sheets.
Sorry, diff/patch are not really inside my toolkit right now.

Starting on line 196:

```

/**
	 * Sends the file to download
	 *
	 * @param	String	$filename
	 */
	public function download( $filename = '') {
		parent::download('text/csv', $filename);
	}
```
to 

```
/**
	 * Sends the file to download
	 *
	 * @param	String	$filename
	 * @param	String	$type
	 */
	public function download($type = '', $filename = '') {
		parent::download('text/csv', $filename);
	}
```

**Comment by AlexEdimensionz** [comment]
Thank you! I patched it in the repo
